import { Injectable, signal } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class TranslateService {
  currentLang = signal<'ru' | 'en'>('ru');

  translations: Record<string, Record<string, string>> = {
    ru: {
      'quickcart': 'QuickCart',
      'categories': 'Категории',
      'discounts': 'Акции 🔥',
      'cart': 'Корзина',
      'logout': 'Выйти',
      'login': 'Войти',
      'search': 'Поиск товаров...',
      'add_product': '+ Добавить продукт',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'add_to_cart': 'В корзину',
      'delete': 'Удалить',
      'not_found': 'Товары не найдены',
      'in_stock': 'В наличии',
      'no_photo': 'Нет фото',
      'all_products': 'Все товары',
      'back': '← Назад',
      'seller': 'Продавец',
      'reviews': 'Отзывы',
      'no_reviews': 'Отзывов пока нет',
      'add_review': 'Оставить отзыв',
      'send': 'Отправить',
      'name': 'Название',
      'description': 'Описание',
      'price': 'Цена',
      'quantity': 'Количество',
      'discount': 'Скидка %',
      'choose_category': 'Выберите категорию',
      'register': 'Регистрация',
      'sign_in': 'Вход',
      'username': 'Логин',
      'email': 'Email',
      'password': 'Пароль',
      'sign_in_btn': 'Войти',
      'register_btn': 'Зарегистрироваться',
      'have_account': 'Уже есть аккаунт? Войти',
      'no_account': 'Нет аккаунта? Зарегистрироваться',
      'buyer': 'Покупатель',
      'seller_role': 'Продавец',
      'cart_title': 'Корзина',
      'cart_empty': 'Корзина пуста',
      'total': 'Итого',
      'order': 'Оформить заказ',
      'remove': 'Удалить',
      'order_success': 'Заказ оформлен!',
    },
    en: {
      'quickcart': 'QuickCart',
      'categories': 'Categories',
      'discounts': 'Sales 🔥',
      'cart': 'Cart',
      'logout': 'Logout',
      'login': 'Login',
      'search': 'Search products...',
      'add_product': '+ Add product',
      'cancel': 'Cancel',
      'save': 'Save',
      'add_to_cart': 'Add to cart',
      'delete': 'Delete',
      'not_found': 'No products found',
      'in_stock': 'In stock',
      'no_photo': 'No photo',
      'all_products': 'All products',
      'back': '← Back',
      'seller': 'Seller',
      'reviews': 'Reviews',
      'no_reviews': 'No reviews yet',
      'add_review': 'Leave a review',
      'send': 'Submit',
      'name': 'Name',
      'description': 'Description',
      'price': 'Price',
      'quantity': 'Quantity',
      'discount': 'Discount %',
      'choose_category': 'Choose category',
      'register': 'Register',
      'sign_in': 'Sign In',
      'username': 'Username',
      'email': 'Email',
      'password': 'Password',
      'sign_in_btn': 'Sign In',
      'register_btn': 'Register',
      'have_account': 'Already have an account? Sign In',
      'no_account': 'No account? Register',
      'buyer': 'Buyer',
      'seller_role': 'Seller',
      'cart_title': 'Cart',
      'cart_empty': 'Cart is empty',
      'total': 'Total',
      'order': 'Place order',
      'remove': 'Remove',
      'order_success': 'Order placed!',
    }
  };

  t(key: string): string {
    return this.translations[this.currentLang()][key] || key;
  }

  toggle() {
    this.currentLang.set(this.currentLang() === 'ru' ? 'en' : 'ru');
  }
}